### ISSUE TITLE
file bigger than 4111568896 bit will cause the file size error

### ISSUE THREAD

**Issue by urack** [lorenzos/Minixed#4] opened 2017-06-14 08:21 UTC
file bigger than 4111568896 bit will cause the file size error.

it will show -179100.0 KB but actually should be 4111568896 bit which will be 3.9G . 
You can check the error on http://ezgo.shishine.com/
Thanks for your support

**Comment by lorenzos** [comment] 2017-06-14 12:40
Duplicate of #2, I'm going to post a comment there.

**Closed as completed by lorenzos** 2017-06-14 12:40 UTC
